export const CAR_LIST_REQUEST = "CAR_LIST_REQUEST";
export const CAR_LIST_SUCCESS = "CAR_LIST_SUCCESS";
export const CAR_LIST_FAIL = "CAR_LIST_FAIL";

export const CAR_DETAILS_REQUEST = "CAR_DETAILS_REQUEST";
export const CAR_DETAILS_SUCCESS = "CAR_DETAILS_SUCCESS";
export const CAR_DETAILS_FAIL = "CAR_DETAILS_FAIL";

export const CAR_READING_REQUEST = "CAR_READING_REQUEST";
export const CAR_READING_SUCCESS = "CAR_READING_SUCCESS";
export const CAR_READING_FAIL = "CAR_READING_FAIL";

export const CAR_REGISTER_REQUEST = "CAR_REGISTER_REQUEST";
export const CAR_REGISTER_SUCCESS = "CAR_REGISTER_SUCCESS";
export const CAR_REGISTER_FAIL = "CAR_DETAILS_FAIL";

export const CAR_UPDATE_REQUEST = "CAR_UPDATE_REQUEST";
export const CAR_UPDATE_SUCCESS = "CAR_UPDATE_SUCCESS";
export const CAR_UPDATE_FAIL = "CAR_UPDATE_FAIL";
export const CAR_UPDATE_RESET = "CAR_UPDATE_RESET";

export const CAR_ADD_MAINTENANCE_REQUEST = "CAR_ADD_MAINTENANCE_REQUEST";
export const CAR_ADD_MAINTENANCE_SUCCESS = "CAR_ADD_MAINTENANCE_SUCCESS";
export const CAR_ADD_MAINTENANCE_FAIL = "CAR_ADD_MAINTENANCE_FAIL";

export const CAR_DETAILS_MAINTENANCE_REQUEST =
	"CAR_DETAILS_MAINTENANCE_REQUEST";
export const CAR_DETAILS_MAINTENANCE_SUCCESS =
	"CAR_DETAILS_MAINTENANCE_SUCCESS";
export const CAR_DETAILS_MAINTENANCE_FAIL = "CAR_DETAILS_MAINTENANCE_FAIL";

export const CAR_UPDATE_MAINTENANCE_REQUEST = "CAR_UPDATE_MAINTENANCE_REQUEST";
export const CAR_UPDATE_MAINTENANCE_SUCCESS = "CAR_UPDATE_MAINTENANCE_SUCCESS";
export const CAR_UPDATE_MAINTENANCE_FAIL = "CAR_UPDATE_MAINTENANCE_FAIL";
export const CAR_UPDATE_MAINTENANCE_RESET = "CAR_UPDATE_MAINTENANCE_RESET";

export const FUEL_DELETE_REQUEST = "FUEL_DELETE_REQUEST";
export const FUEL_DELETE_SUCCESS = "FUEL_DELETE_SUCCESS";
export const FUEL_DELETE_FAIL = "FUEL_DELETE_FAIL";
