export const DRIVER_LIST_REQUEST = "DRIVER_LIST_REQUEST";
export const DRIVER_LIST_SUCCESS = "DRIVER_LIST_SUCCESS";
export const DRIVER_LIST_FAIL = "DRIVER_LIST_FAIL";

export const DRIVER_DETAILS_REQUEST = "DRIVER_DETAILS_REQUEST";
export const DRIVER_DETAILS_SUCCESS = "DRIVER_DETAILS_SUCCESS";
export const DRIVER_DETAILS_FAIL = "DRIVER_DETAILS_FAIL";

export const DRIVER_REGISTER_REQUEST = "DRIVER_REGISTER_REQUEST";
export const DRIVER_REGISTER_SUCCESS = "DRIVER_REGISTER_SUCCESS";
export const DRIVER_REGISTER_FAIL = "DRIVER_REGISTER_FAIL";

export const DRIVER_UPDATE_REQUEST = "DRIVER_UPDATE_REQUEST";
export const DRIVER_UPDATE_SUCCESS = "DRIVER_UPDATE_SUCCESS";
export const DRIVER_UPDATE_FAIL = "DRIVER_UPDATE_FAIL";
export const DRIVER_UPDATE_RESET = "DRIVER_UPDATE_RESET";
