export const ADD_EXPENSE_REQUEST = "ADD_EXPENSE_REQUEST";
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS";
export const ADD_EXPENSE_FAIL = "ADD_EXPENSE_FAIL";

export const EXPENSE_LIST_REQUEST = "EXPENSE_LIST_REQUEST";
export const EXPENSE_LIST_SUCCESS = "EXPENSE_LIST_SUCCESS";
export const EXPENSE_LIST_FAIL = "EXPENSE_LIST_FAIL";

export const EXPENSE_UPDATE_REQUEST = "EXPENSE_UPDATE_REQUEST";
export const EXPENSE_UPDATE_SUCCESS = "EXPENSE_UPDATE_SUCCESS";
export const EXPENSE_UPDATE_FAIL = "EXPENSE_UPDATE_FAIL";

export const EXPENSE_UPDATE_DEPARTMENT_REQUEST =
	"EXPENSE_UPDATE_DEPARTMENT_REQUEST";
export const EXPENSE_UPDATE_DEPARTMENT_SUCCESS =
	"EXPENSE_UPDATE_DEPARTMENT_SUCCESS";
export const EXPENSE_UPDATE_DEPARTMENT_FAIL = "EXPENSE_UPDATE_DEPARTMENT_FAIL";
