export const JOURNEY_LIST_REQUEST = "JOURNEY_LIST_REQUEST";
export const JOURNEY_LIST_SUCCESS = "JOURNEY_LIST_SUCCESS";
export const JOURNEY_LIST_FAIL = "JOURNEY_LIST_FAIL";

export const JOURNEY_UPDATE_REQUEST = "JOURNEY_UPDATE_REQUEST";
export const JOURNEY_UPDATE_SUCCESS = "JOURNEY_UPDATE_SUCCESS";
export const JOURNEY_UPDATE_FAIL = "JOURNEY_UPDATE_FAIL";

export const JOURNEY_READING_REQUEST = "JOURNEY_READING_REQUEST";
export const JOURNEY_READING_SUCCESS = "JOURNEY_READING_SUCCESS";
export const JOURNEY_READING_FAIL = "JOURNEY_READING_FAIL";

export const JOURNEY_DETAILS_REQUEST = "JOURNEY_DETAILS_REQUEST";
export const JOURNEY_DETAILS_SUCCESS = "JOURNEY_DETAILS_SUCCESS";
export const JOURNEY_DETAILS_FAIL = "JOURNEY_DETAILS_FAIL";
